# Generated by Django 4.2.7 on 2023-11-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
