# Generated by Django 4.2.7 on 2023-11-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_emaildata_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.emaildata')),
            ],
            options={
                'verbose_name': 'Task Database',
                'verbose_name_plural': 'Task Database',
            },
        ),
    ]
