# Generated by Django 4.2.7 on 2023-11-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_taskdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdb',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
